language: java
install: mvn clean install
notifications:
  email:
    on_success: never
sudo: false
env:
  global:
    - Foo: "foo"
    - secure: "iZlQMG+bPsoJv5+BI3Nk3LiFnr70c41NuWsQS0ert+hA5F3TKGOsyARNYkIP4BiRgU6XZHPGhC8HPLJysjCw2SCgJgAvav0yZ4PrMh7p1rZMzUI8k0pl1FetWHahA3PJrLPazB7rwpkGcGeJl+6xxitAT0V1Soa4AM5RiCaMY0gvpzwYwGLsXeaCmLG2PvSxmBQA8HzcMnBsweFMi/G9dlujP3BwBsxjb9MPa0eFcXnne4RjqJj0MQqglfPPZFwGIEZVCCA3Gs1exbf+ZgH/wYSvmYgrQo3Wci4TXWrK+q8G7rlSfRtWSvxbIlYCM02dTx1eXGnvd/t3OIWXNso/fLnH5qJunI6yHcQndCUyaq+bo1akQJs+eEzoJ0WNkzjtuAkmzMqypNKsPX0tYysw4bQ1B8yNeudSI17wDYQMud7vsApJbjX9Zb1ZuILNc5Br5xjzBmhiyynzt1TUOD2BD5oHf/wrpiwaS/GTu1QwPqGYnqpxFK+q0G06yXMvHNNmKwTNojZpPS8eLFk4v3F19G5dsHdUvq1LhFP+wn1AwoucOAdn0uBWqXDvFm8Se6VqtGCroCodENMeJLFZ9xL+ZqlsLrQkOu3Zo69ydDRXv50UeEjQroaRwKgJ+lsP+jXsI6YVS9L4DTFnezUIfTu9CkpRDF7O4wMDwqtmC+yEkjc="
