language: java
install: mvn clean install
notifications:
  email:
    on_success: never
sudo: false
env:
  global:
  - secure: kIpR2L0Sk+2NrQyJvnh2nhDl3nlO08ga9brzjXQzsrwaQNzpthbVA2S5hNudYzXqVWEB8Vs9JTcwtjfH3h0DghE7O39kFSiH8Y6I4DV5X8QXTQMh/jXyPhODbeAC4ItyEOFOGkma1zgcYAUJqC+MQuHd6fJK5ReHCP4PdrM34YHKfxzZyQ6hQQtnOBQoTFQRCowIuE/laIcDH1sG0pf0ocVrZVvEPRO3A/tSpPeupZ0Ydj+qo/f4CGBuKF++kUrkbfNYYYE5Ip+BoDVvFw4khYaPrcYfyWl4riljATs8GD4LiIXNgUwu0Buinzk0CvSgyJ8mQYszYUZBUUYgYHdpkjqkowY0s2Listi33qoAAx0uRboqOKEXaUJsrMzmjJYYEv/8fJQ80ebZVjM8Tq0H0moZXru/BJ4hJ2rad3oKkG7G8a1/yNYtaGjSeXuQPKl4TUUWkf+YMIiZtst9IRwQm04CdX0jPY88KtieR+ST7qlrrnHvb5vfyJQRq+xihovrrwRMnADM8K0bIXmjToxRvxkJKEyxSRFRwAV6aKN/3kityL83sBktHdyFFqoqPMNX8H1dsXysQcrMqfU98NnsJ2Q2M3ppnLQgGkXW7nB87rssO+mDMZnMEbygfRMwL+ZD4Pn+lKqM/L0HzTjWceJlPGhZsJt+fNsLSznFWndJoOc=
