language: java
install: mvn clean install
notifications:
  email:
    on_success: never
sudo: false
env:
  global:
  - appClientId=27801
  - secure: EX+h4BjG4nxtqD734hY76Vrct/ZEZuG8597NA/O1zxVyHcBZBOX9b9Ew49T9u1cWOj+yx5HDqy78T1Ens0h6lRJ50Kg2/0ZXFzryPswxZMNfPeaSMr6zhK8TQumIpY1U9qsmofRS0W4Hos5GPqu1xk2SsOvAEemMbOOBeUPkq6Q13MZcF855P5xrrOuJVsVoNfDkrat6MqzCRvLjj59saEHfqT9O9FgfkYSD8GfYP7pfEN9aToQTAu7xX/6N69/oLXxZLjK5OWS1HOUeYTzuX7FAsgy6MenRolm7FXCmRUBo6ICWLKUuT2luCzk1fbBn92zi3cCD7zmYbBVNSp7DK58BS+XxoA3NBihgXRojf6Ec0z/9Wlp/nt2DN3DW1biIcNzrxOaq0AgSlRlXUhF6CLSHiZFGq2x2jNVmI+dRG2TGjnDr9enmGR3msVIe4sP1nCPswRqq3KZPS9ivcmmY7OwZSSGlw0EfRv3+eRObMl6tmu0iNBbbKFRig76CYsnsiQp6bNINSdBw+2lWOeGeIG3hD89MlIVL2g8HVGHs78jG3xgiOE7/YhBrxl53AY6wgV+AYucvP1U4zJAmZHmbYnqNaBwhzqwtmyY93PfEoDgTt3QudTA7Mj2MdWAQECVCV+bZmhHf62+AGWayJtPr08kN2HNuD8MrQeK/flh712g=
